server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0 # Binds to all network interfaces so Docker bridge can connect
  servlet:
    context-path: /
    session:
      timeout: 3600 # redefine default 30m by 1 hour
  compression:
    enabled: true
    min-response-size: 1024

app:
  authorization-request-timeout: 10 # min
  application-url: "${APPLICATION_URL:http://localhost:8080}"
  logout-url: "${LOGOUT_URL:http://localhost:8080/logout}"

info:
  app:
    name: ti-gateway-api
    version: '@project.version@'

spring:
  application:
    name: ${info.app.name}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
      enabled: true
  security:
    oauth2:
      client:
        registration:
          okta:
            provider: okta
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - given_name
              - family_name
            client-id: ${OKTA_OAUTH2_CLIENT_ID}
            client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}
            redirect-uri: ${app.application-url}/login/oauth2/code/okta
        provider:
          okta:
            issuer-uri: https://${OKTA_DOMAIN}/
  data:
    redis:
      ssl:
        enabled: ${SESSION_SSL_ENABLED:false}
      host: ${SESSION_CACHE_HOST:127.0.0.1}
      port: ${SESSION_CACHE_PORT:6379}
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  # spring.mvc.pathmatch.matching-strategy=ant_path_matcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

okta:
  logout-url: https://${OKTA_DOMAIN}/v2/logout?client_id=${OKTA_OAUTH2_CLIENT_ID}&returnTo=${ms.client-to-url.knowledge-url}/relogin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    prometheus:
      access: read_only

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
    export:
      zipkin:
        enabled: true
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}


#  otlp:
#    tracing:
#      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
#      transport: http

# Enable Native JSON Structured Logging (Spring Boot 3.4+)
logging:
  level:
    com.wk.ti: debug
    org.springframework: info
  structured:
    format:
      console: ecs # Emits logs in ECS JSON format containing service, traceId, spanId

rate:
  limiting:
    enabled: ${LP_RATE_LIMITING_ENABLED:true}
    capacity: ${LP_RATE_LIMITING_CAPACITY:100}
    refill: ${LP_RATE_LIMITING_REFILL:100}
    refill-period: ${LP_RATE_LIMITING_PERIOD:1m}   # minutes
    exclude:
      - /actuator/**
      - /swagger-ui/**
      - /v3/api-docs/**

ms:
  cors:
    allowed-origins: ${ms.services.dashboard-base-url}
  origin: ${APPLICATION_URL:http://localhost:8080}
  services:
    dashboard-base-url: "${KNOWLEDGE_BASE_URL:http://localhost:5000}"
  client-to-url:
    knowledge-url: "${KNOWLEDGE_BASE_URL:http://localhost:5000}/dashboard-page"
  service-name-to-uri:
    knowledge: http://${KNOWLEDGE_SERVICE:localhost}:${KNOWLEDGE_SERVICE_PORT:8081}
    orchestrator: http://${ORCHESTRATOR_SERVICE:localhost}:${ORCHESTRATOR_SERVICE_PORT:8082}
    import: http://${IMPORT_SERVICE:localhost}:${IMPORT_SERVICE_PORT:8083}
    export: http://${EXPORT_SERVICE:localhost}:${EXPORT_SERVICE_PORT:8084}
    notification: http://${NOTIFICATION_SERVICE:localhost}:${NOTIFICATION_SERVICE_PORT:8085}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: "01 - Knowledge Service"
        url: "${ms.origin}/knowledge/v3/api-docs"
      - name: "02 - Orchestrator Service"
        url: "${ms.origin}/orchestrator/v3/api-docs"
      - name: "03 - Import Service"
        url: "${ms.origin}/import/v3/api-docs"
      - name: "04 - Export Service"
        url: "${ms.origin}/export/v3/api-docs"
      - name: "05 - Notification Service"
        url: "${ms.origin}/notification/v3/api-docs"
