services:
  ti-document-db:
    image: ankane/pgvector
    container_name: ti-document-db
    environment:
      POSTGRES_DB: ${DOCUMENT_DB_NAME:-document_db}
      POSTGRES_USER: ${DOCUMENT_USER:-postgres}
      POSTGRES_PASSWORD: ${DOCUMENT_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - document-db-data:/var/lib/postgresql/data
      - ./document-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - knowledge-network

  ti-document-liquibase:
    image: mnpma/liquibase-pg:5.0
    container_name: ti-document-liquibase
    volumes:
      # Relative path targeting a directory outside the current project root
      - ../../ti-document-db/resources/liquibase:/liquibase/changelog
    networks:
      - knowledge-network
    command:
      - --url=jdbc:postgresql://ti-document-db:5432/${DOCUMENT_DB_NAME:-document_db}
      - --username=${DOCUMENT_USER:-postgres}
      - --password=${DOCUMENT_PASSWORD:-postgres}
      - --changeLogFile=liquibase-changelog.xml
      - --contexts=dev
      - update
    depends_on:
      - ti-document-db

networks:
  knowledge-network:
    name: knowledge-network
volumes:
  document-db-data: