global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ti-platform-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'localhost:8080' # gateway-api
          - 'localhost:8081' # knowledge-api

#          - 'ti-orchestrator-api:8082'
#          - 'ti-import-api:8083'
#          - 'ti-export-api:8084'
#          - 'ti-audit-api:8085'
#          - 'ti-notification-api:8086'