global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ti-platform-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          # Uncomment below if testing Spring Boot running locally in IntelliJ:
          - 'localhost:8080'
          - 'ti-knowledge-api:8081'
#          - 'ti-orchestrator-api:8082'
#          - 'ti-import-worker:8083'
#          - 'ti-export-api:8084'
#          - 'ti-ai-orchestrator-api:8085'
#          - 'ti-document-worker:8086'
#          - 'ti-document-agent:8087'
#          - 'ti-sql-agent:8088'
