global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ti-platform-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'localhost:8080' # gateway-api
          - 'localhost:8081' # knowledge-api
          - 'localhost:8082' # orchestrator-api
          - 'localhost:8083' # import-worker
          - 'localhost:8084' # export-api
          - 'localhost:8085' # ai-orchestrator-api
          - 'localhost:8086' # document-worker
          - 'localhost:8087' # document-agent
          - 'localhost:8088' # sql-agent