name: Build and package

on:
  push:
    branches: [main, 'feature/**']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21 and cache Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build (package)
        run: ./mvnw -B -U -V -DskipTests package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  publish:
    name: Publish to GHCR
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      - name: Lowercase repository name for image tag
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Login to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image and push to GHCR
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:ci-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
      - name: Remove local images
        run: |
            docker image rm ${{ env.IMAGE_NAME }}:ci-${{ github.sha }}
            docker image rm ${{ env.IMAGE_NAME }}:latest
